name: fl_clash
description: A multi-platform proxy client based on ClashMeta, simple and easy to use, open-source and ad-free.
publish_to: 'none'
version: 0.8.88+2025090501
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  window_manager: ^0.5.0
  dynamic_color: ^1.8.1
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: ^0.5.1
  json_annotation: ^4.9.0
  file_picker: ^10.3.1
  mobile_scanner: ^7.0.0
  app_links: ^6.4.0
  win32_registry: ^2.0.0
  tray_manager: ^0.5.0
  collection: ^1.18.0
  animations: ^2.0.11
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  freezed_annotation: ^3.1.0
  image_picker: ^1.1.2
  ffi: ^2.1.4
  webdav_client: ^1.2.2
  dio: ^5.8.0+1
  win32: ^5.5.1
  re_editor:
    git:
      url: https://github.com/chen08209/re-editor.git
      ref: main
  re_highlight: ^0.0.3
  archive: ^4.0.7
  emoji_regex: ^0.0.5
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  riverpod: ^3.0.0-dev.17
  material_color_utilities: ^0.11.1
  flutter_js:
    git:
      url: https://github.com/chen08209/flutter_js
      ref: master
  flutter_svg: ^2.1.0
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.7.0
  args: ^2.4.2
  freezed: ^3.2.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n