name: fl_clash
description: A multi-platform proxy client based on ClashMeta, simple and easy to use, open-source and ad-free.
publish_to: 'none'
version: 0.8.92+2026020201
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1
  dynamic_color: ^1.8.1
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: ^0.5.1
  json_annotation: ^4.9.0
  file_picker: ^10.3.3
  mobile_scanner: ^7.0.1
  app_links: ^6.4.0
  win32_registry: ^2.0.0
  tray_manager:
    path: plugins/tray_manager/packages/tray_manager
  collection: ^1.19.1
  animations: ^2.1.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.0
  ffi: ^2.1.4
  webdav_client: ^1.2.2
  dio: ^5.8.0+1
  win32: ^5.5.1
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  archive: ^4.0.7
  emoji_regex: ^0.0.5
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^12.2.0
  connectivity_plus: ^7.0.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  riverpod: ^3.0.0
  material_color_utilities: ^0.11.1
  flutter_js:
    git:
      url: https://github.com/chen08209/flutter_js
      ref: master
  flutter_svg: ^2.1.0
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  yaml: ^3.1.3
  yaml_writer:
    git:
      url: https://github.com/chen08209/yaml_writer
      ref: master
  super_sliver_list: ^0.4.1

  drift: ^2.29.0
  drift_flutter: ^0.2.7
  fractional_indexing: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.7.1
  args: ^2.4.2
  freezed: ^3.2.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

  drift_dev: ^2.29.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatar/
    - assets/images/empty/
    - assets/images/icon/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n